<!DOCTYPE html>
<html>
<style>
  input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  input[type=submit]:hover {
    background-color: #45a049;
  }

  div {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
  }
</style>

<body style="margin: 20px;">

<a href="/" style="text-decoration: none; font-size: 25px;">Go To Home</a> <br><br>

<?php echo '<h3>Create New Student Recode</h3>'; ?>

<div>
  <form action='/crtstud' autocomplete="off" method="post">

    <label for='roll'>Roll Number</label>
    <input type='text' id='roll' name='roll'>

    <label for='name'>Student Name</label>
    <input type='text' id='name' name='name' >

    <label for='marks'>Marks</label>
    <input type='text' id='marks' name='marks' >

    <input type="submit" value="Submit">

  </form>
</div>

</body>
</html>
